RSpec.describe Cborb::Decoding::IB_JUMP_TABLE do
  # https://tools.ietf.org/html/rfc7049#appendix-B
  it "Be set correct table" do
    expect(Cborb::Decoding::IB_JUMP_TABLE).to eq [
      # 0x00 ~
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,

      # 0x10 ~
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer,
      Cborb::Decoding::Types::Integer, # 0x1B
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,

      # 0x20 ~
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,

      # 0x30 ~
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger,
      Cborb::Decoding::Types::NegativeInteger, # 0x3B
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,

      # 0x40 ~
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,

      # 0x50 ~
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString,
      Cborb::Decoding::Types::ByteString, # 0x5B
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::IndefiniteByteString, # 0x5F

      # 0x60 ~
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,

      # 0x70 ~
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString,
      Cborb::Decoding::Types::TextString, # 0x7B
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::IndefiniteTextString, # 0x7F

      # 0x80 ~
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,

      # 0x90 ~
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array,
      Cborb::Decoding::Types::Array, # 0x9B
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::IndefiniteArray, # 0x9F

      # 0xA0 ~
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,

      # 0xB0 ~
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map,
      Cborb::Decoding::Types::Map, # 0xBB
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::IndefiniteMap, # 0xBF

      # 0xC0 ~
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,

      # 0xD0 ~
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag,
      Cborb::Decoding::Types::Tag, # 0xDB
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,
      Cborb::Decoding::Types::Unknown,

      # 0xE0 ~
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,

      # 0xF0 ~
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue, # 0xF3
      Cborb::Decoding::Types::SimpleValue,
      Cborb::Decoding::Types::SimpleValue,
      Cborb::Decoding::Types::SimpleValue,
      Cborb::Decoding::Types::SimpleValue,                # 0xF7
      Cborb::Decoding::Types::UnassignedSimpleValue,      # 0xF8
      Cborb::Decoding::Types::HalfPrecisionFloatingPoint, # 0xF9
      Cborb::Decoding::Types::FloatingPoint,              # 0xFA
      Cborb::Decoding::Types::FloatingPoint,              # 0xFB
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::UnassignedSimpleValue,
      Cborb::Decoding::Types::Break,                      # 0xFF
    ]
  end
end
